version: '3'

services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=256m
      - JVM_XMX=256m
    volumes:
      - /yao/nacos/standalone-logs/:/home/nacos/logs
      - /yao/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
    restart: on-failure